name: CI

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '23 1 * * 0'
  workflow_dispatch:

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install .

      - name: Run tests
        run: tox -m test

  linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade .[lint]

      - name: Run ruff
        run: ruff check --output-format github

  finalise:
    runs-on: ubuntu-latest
    needs: [testing, linting]
    steps:
      - name: finalise
        run: echo "All done"
